### ISSUE TITLE
Fast Trading Bug

### ISSUE THREAD

**Issue by Akuwau** [SriroEsi/GRO#7]
It is possible to buy/sell fast enough to trick the game into giving you both credits and your item(s) back.
... But once the credits are spent again, the item(s) disappear, and/or credits are removed.

Tested with macros intended for the first effect; Duplication.

**Comment by Akuwau** [comment]
This bug also occurred with a macro that held down the RMB of "multiple mice" at the same time / on the same point, in an attempt to buy multiple items at the same time.
The game corrected itself again in these cases.

**Comment by SriroEsi** [comment]
You can get a sync error where you buy items so fast the server can't send updates.  However it will correct its self  the next time you buy an item or relog.
